import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { getPublishedProject, getPublishedProjects } from "@/lib/studio-data";
import { ActionLink, ResponsiveMedia } from "@/components/ui/primitives";
import "./case-study.css";

type Props={params:Promise<{slug:string}>};
export async function generateStaticParams(){return (await getPublishedProjects()).map(({slug})=>({slug}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const project=await getPublishedProject(slug);if(!project)return{};return{title:project.name,description:project.summary,alternates:{canonical:`/work/${slug}`},openGraph:{title:`${project.name} — Taoshiflex Studio`,description:project.summary,url:`/work/${slug}`}}}
export default async function CaseStudy({params}:Props){const {slug}=await params;const projects=await getPublishedProjects();const project=await getPublishedProject(slug);if(!project)notFound();const index=projects.findIndex((item)=>item.slug===slug);const next=projects[(index+1)%projects.length];return <article className="case" style={{"--project-accent":project.accent} as React.CSSProperties}><header className="case-hero container"><p className="eyebrow">{project.category} / {project.year}</p><h1 className="display">{project.name}</h1><p>{project.summary}</p><dl><div><dt>Client / business</dt><dd>{project.client}</dd></div><div><dt>Status</dt><dd>{project.status}</dd></div><div><dt>Capabilities</dt><dd>{project.capabilities.join(", ")}</dd></div></dl></header><div className="container"><ResponsiveMedia accent={project.accent} label={`${project.name} primary project view`} className="case-cover"/></div><section className="case-narrative container"><p className="eyebrow">The context</p><h2>{project.challenge}</h2><div><p>{project.context}</p><p>{project.approach}</p></div></section><section className="case-solution"><div className="container"><p className="eyebrow">Approach → Solution</p><h2 className="display display-md">A system designed around the work.</h2><p className="solution-lede">{project.solution}</p><div className="case-media-grid">{project.media.map((media)=><ResponsiveMedia key={media.id} accent={project.accent} label={media.alt}/>)}</div></div></section><section className="case-details container"><div><p className="eyebrow">System / Features</p><ul>{project.features.map((item)=><li key={item}>{item}</li>)}</ul></div><div><p className="eyebrow">Technical notes</p><ul>{project.technicalNotes.map((item)=><li key={item}>{item}</li>)}</ul></div><div className="result"><p className="eyebrow">Current result</p><p>{project.result}</p></div></section><footer className="case-next container"><p className="eyebrow">Next project</p>{next?<Link href={`/work/${next.slug}`}>{next.name}<span aria-hidden>↗</span></Link>:null}<ActionLink href="/start-a-project" solid>Start a Project</ActionLink></footer></article>}
