"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import type { AssistantSettings, ServicePackage } from "@/types/content";

type Message={role:"assistant"|"user";text:string};
const money=(value:number)=>new Intl.NumberFormat("en-BD").format(value);
function answer(input:string,settings:AssistantSettings,packages:ServicePackage[]){
  if(settings.knowledgeCategories.includes("pricing")&&settings.showPricing&&/price|cost|budget|bdt|taka/i.test(input)){if(!packages.length)return "No public package is active right now. Use the project brief for a scope-specific conversation.";return packages.map(item=>`${item.name}: ${item.priceFrom===null?"custom quote":`from ৳${money(item.priceFrom)}`}`).join("\n")}
  if(settings.knowledgeCategories.includes("services")&&/time|long|delivery|week|start/i.test(input)){if(!packages.length)return "Delivery timing is confirmed after scope review.";return packages.map(item=>`${item.name}: ${item.deliveryEstimate}`).join("\n")}
  if(settings.knowledgeCategories.includes("services")&&/shop|commerce|store|payment/i.test(input))return "Commerce work can include catalog, search, cart, checkout, cash on delivery and payment setup where verified merchant accounts are available. Courier API work is separately scoped.";
  if(settings.knowledgeCategories.includes("process")&&/process|work|how/i.test(input))return "The Studio moves through discovery, direction, design, build and launch. Each stage reduces ambiguity before engineering effort compounds.";
  if(settings.knowledgeCategories.includes("projects")&&/project|portfolio|case/i.test(input))return "Selected work contains only admin-curated, published projects. In-progress work is labelled honestly and avoids unverified performance claims.";
  return "I can answer from the Studio’s approved services, active pricing, process and published-work knowledge. For a project-specific answer, send a brief.";
}
export function StudioAssistant({settings,packages}:{settings:AssistantSettings;packages:ServicePackage[]}){const [open,setOpen]=useState(false);const [input,setInput]=useState("");const [messages,setMessages]=useState<Message[]>([{role:"assistant",text:settings.greeting}]);const reduce=useReducedMotion();if(!settings.enabled)return null;function submit(event:FormEvent){event.preventDefault();const value=input.trim();if(!value)return;const additions:Message[]=[{role:"user",text:value},{role:"assistant",text:answer(value,settings,packages)}];setMessages(current=>[...current,...additions].slice(-(settings.maximumMessages+1)));setInput("")}return <div className="assistant"><AnimatePresence>{open?<motion.section className="assistant-panel" role="dialog" aria-label={settings.name} initial={reduce?false:{opacity:0,y:16,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:10}}><header><div><small>Curated guidance / Rule-based</small><strong>{settings.name}</strong></div><button type="button" onClick={()=>setOpen(false)} aria-label={`Close ${settings.name}`}>×</button></header><div className="assistant-log" aria-live="polite">{messages.map((message,index)=><div key={`${message.role}-${index}`} className={`assistant-message ${message.role}`}><small>{message.role==="assistant"?"Studio":"You"}</small><p>{message.text}</p></div>)}</div><form onSubmit={submit}><label htmlFor="studio-question">Ask a question</label><div><input id="studio-question" value={input} maxLength={240} onChange={event=>setInput(event.target.value)} placeholder="What does a business website include?"/><button>Send</button></div></form>{settings.leadCapture?<Link href={settings.handoffUrl}>Discuss a real project →</Link>:null}</motion.section>:null}</AnimatePresence><button className="assistant-trigger" type="button" onClick={()=>setOpen(value=>!value)} aria-expanded={open}>{open?"Close":"Ask the Studio"}</button></div>}
