"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";

type Message={role:string;text:string};
const answers=[
  {test:/price|cost|budget|bdt|taka/i,text:"Studio packages currently start at ৳14,999 for a focused one-page website and ৳27,999 for a business website. Commerce starts at ৳49,999; custom platforms are scoped after discovery."},
  {test:/time|long|delivery|week|start/i,text:"Typical starting windows range from 5–7 working days for a focused one-page site to about 28 working days for advanced commerce. Final timing depends on verified scope and content readiness."},
  {test:/shop|commerce|store|payment/i,text:"Commerce work can include catalog, search, cart, checkout, cash on delivery and payment setup where verified merchant accounts are available. Courier API work is separately scoped."},
  {test:/process|work|how/i,text:"The Studio moves through discovery, direction, design, build and launch. Each stage exists to reduce ambiguity before engineering effort compounds."},
  {test:/project|portfolio|case/i,text:"The selected work page contains only admin-curated, published projects. In-progress work is labelled honestly and avoids unverified performance claims."},
];
function reply(input:string){return answers.find(item=>item.test.test(input))?.text||"I can help with services, starting prices, process and published work. For a project-specific answer, send a brief and the founder will reply directly."}
export function StudioAssistant(){const [open,setOpen]=useState(false);const [input,setInput]=useState("");const [messages,setMessages]=useState<Message[]>([{role:"assistant",text:"What are you planning to build? Ask about scope, pricing or process."}]);const reduce=useReducedMotion();function submit(event:FormEvent){event.preventDefault();const value=input.trim();if(!value)return;setMessages(current=>[...current,{role:"user",text:value},{role:"assistant",text:reply(value)}].slice(-9));setInput("")}return <div className="assistant"><AnimatePresence>{open?<motion.section className="assistant-panel" role="dialog" aria-label="Studio Assistant" initial={reduce?false:{opacity:0,y:16,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:10}}><header><div><small>Curated knowledge / No AI claims</small><strong>Studio Assistant</strong></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close Studio Assistant">×</button></header><div className="assistant-log" aria-live="polite">{messages.map((message,index)=><p key={`${message.role}-${index}`} className={message.role}>{message.text}</p>)}</div><form onSubmit={submit}><label htmlFor="studio-question">Ask a question</label><div><input id="studio-question" value={input} maxLength={240} onChange={event=>setInput(event.target.value)} placeholder="What does a business website include?"/><button>Send</button></div></form><Link href="/start-a-project">Discuss a real project →</Link></motion.section>:null}</AnimatePresence><button className="assistant-trigger" type="button" onClick={()=>setOpen(value=>!value)} aria-expanded={open}>{open?"Close":"Ask the Studio"}</button></div>}
