import { authorizeMutation, cleanText } from "@/lib/admin-security";
import { parseMoney, paymentMethods, type PaymentScheduleItem, type ProjectBilling } from "@/lib/commercial";
import { supabaseRest } from "@/lib/supabase-rest";
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const validId=(value:unknown):value is string=>typeof value==="string"&&uuid.test(value);
const date=(value:unknown)=>typeof value==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(value)?value:null;
export async function POST(request:Request){const auth=await authorizeMutation(request);if(auth.error)return auth.error;const b=await request.json().catch(()=>null) as Record<string,unknown>|null,kind=cleanText(b?.kind,30,true),projectId=b?.projectId;if(!kind||!validId(projectId))return Response.json({error:"Valid billing operation required."},{status:400});try{
 if(kind==="initialize"){const currency=cleanText(b?.currency,3,true)?.toUpperCase(),decimals=Number(b?.decimals??2),amount=parseMoney(b?.projectValue,decimals),deposit=Number(b?.depositPercentage??30);if(!currency||!amount||!Number.isInteger(decimals)||decimals<0||decimals>3||!Number.isFinite(deposit)||deposit<=0||deposit>=100)return Response.json({error:"Enter a valid project value, currency and deposit percentage."},{status:400});await supabaseRest("rpc/initialize_project_billing",{method:"POST",body:JSON.stringify({target_project_id:projectId,project_value_minor:amount,project_currency:currency,decimal_places:decimals,deposit_percentage:deposit})},{userAccessToken:auth.token});return Response.json({ok:true});}
 if(kind==="schedule"){const billing=(await supabaseRest<ProjectBilling[]>(`project_billing?project_id=eq.${projectId}&select=*&limit=1`,{},"privileged"))[0],label=cleanText(b?.label,120,true),amount=billing&&parseMoney(b?.amount,billing.currency_decimals),percentage=b?.percentage===""||b?.percentage==null?null:Number(b.percentage);if(!billing||!label||!amount||percentage!==null&&(!Number.isFinite(percentage)||percentage<=0||percentage>100))return Response.json({error:"Review the installment fields."},{status:400});const current=await supabaseRest<PaymentScheduleItem[]>(`project_payment_schedule?project_id=eq.${projectId}&archived_at=is.null&select=expected_amount_minor`,{},"privileged");if(current.reduce((sum,item)=>sum+item.expected_amount_minor,0)+amount>billing.agreed_value_minor)return Response.json({error:"Active installment amounts cannot exceed the agreed project value."},{status:400});await supabaseRest("project_payment_schedule",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({project_id:projectId,label,expected_amount_minor:amount,percentage,due_date:date(b?.dueDate),sort_order:current.length})},"privileged");return Response.json({ok:true});}
 if(kind==="manual"){const billing=(await supabaseRest<ProjectBilling[]>(`project_billing?project_id=eq.${projectId}&select=*&limit=1`,{},"privileged"))[0],method=cleanText(b?.method,30,true),amount=billing&&parseMoney(b?.amount,billing.currency_decimals),scheduleId=validId(b?.scheduleItemId)?b.scheduleItemId:null;if(!billing||!amount||!method||!paymentMethods.includes(method as typeof paymentMethods[number]))return Response.json({error:"Review the manual payment fields."},{status:400});await supabaseRest("rpc/record_manual_project_payment",{method:"POST",body:JSON.stringify({target_project_id:projectId,target_schedule_item_id:scheduleId,payment_amount_minor:amount,method,transaction_reference:cleanText(b?.referenceId,160)||"",payment_note:cleanText(b?.note,1000)||""})},{userAccessToken:auth.token});return Response.json({ok:true});}
 return Response.json({error:"Unsupported billing action."},{status:400});
}catch{return Response.json({error:"Billing action could not be completed."},{status:409})}}
export async function PATCH(request:Request){const auth=await authorizeMutation(request);if(auth.error)return auth.error;const b=await request.json().catch(()=>null) as Record<string,unknown>|null,kind=cleanText(b?.kind,30,true),projectId=b?.projectId;if(!kind||!validId(projectId))return Response.json({error:"Valid billing operation required."},{status:400});try{
 if(kind==="settings"){const existing=(await supabaseRest<ProjectBilling[]>(`project_billing?project_id=eq.${projectId}&select=*&limit=1`,{},"privileged"))[0],amount=existing&&parseMoney(b?.projectValue,existing.currency_decimals),instructions=cleanText(b?.instructions,4000),methods=Array.isArray(b?.methods)?b.methods.filter((x):x is typeof paymentMethods[number]=>typeof x==="string"&&paymentMethods.includes(x as typeof paymentMethods[number])):[];if(!existing||!amount||instructions===null||!methods.length)return Response.json({error:"Review billing settings."},{status:400});const schedule=await supabaseRest<PaymentScheduleItem[]>(`project_payment_schedule?project_id=eq.${projectId}&archived_at=is.null&select=expected_amount_minor`,{},"privileged");if(schedule.reduce((sum,item)=>sum+item.expected_amount_minor,0)>amount)return Response.json({error:"Project value cannot be lower than the active payment schedule."},{status:400});await supabaseRest(`project_billing?project_id=eq.${projectId}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({agreed_value_minor:amount,allowed_methods:methods,payment_instructions:instructions})},"privileged");return Response.json({ok:true});}
 if(kind==="schedule"){const id=b?.id;if(!validId(id))return Response.json({error:"Valid schedule item required."},{status:400});const billing=(await supabaseRest<ProjectBilling[]>(`project_billing?project_id=eq.${projectId}&select=*&limit=1`,{},"privileged"))[0],label=cleanText(b?.label,120,true),amount=billing&&parseMoney(b?.amount,billing.currency_decimals),percentage=b?.percentage===""||b?.percentage==null?null:Number(b.percentage);if(!billing||!label||!amount||percentage!==null&&(!Number.isFinite(percentage)||percentage<=0||percentage>100))return Response.json({error:"Review the installment fields."},{status:400});const others=await supabaseRest<PaymentScheduleItem[]>(`project_payment_schedule?project_id=eq.${projectId}&id=neq.${id}&archived_at=is.null&select=expected_amount_minor`,{},"privileged");if(others.reduce((sum,item)=>sum+item.expected_amount_minor,0)+amount>billing.agreed_value_minor)return Response.json({error:"Active installment amounts cannot exceed the agreed project value."},{status:400});await supabaseRest(`project_payment_schedule?id=eq.${id}&project_id=eq.${projectId}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({label,expected_amount_minor:amount,percentage,due_date:date(b?.dueDate)})},"privileged");return Response.json({ok:true});}
 if(kind==="schedule-order"){if(!Array.isArray(b?.orderedIds)||b.orderedIds.some(item=>!validId(item)))return Response.json({error:"Valid installment order required."},{status:400});const ids=[...new Set(b.orderedIds as string[])],rows=await supabaseRest<PaymentScheduleItem[]>(`project_payment_schedule?project_id=eq.${projectId}&archived_at=is.null&select=id`,{},"privileged");if(rows.length!==ids.length||rows.some(row=>!ids.includes(row.id)))return Response.json({error:"Installments changed. Refresh and try again."},{status:409});await Promise.all(ids.map((id,sort_order)=>supabaseRest(`project_payment_schedule?id=eq.${id}&project_id=eq.${projectId}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({sort_order})},"privileged")));return Response.json({ok:true});}
 if(kind==="decision"){const paymentId=b?.paymentId,decision=cleanText(b?.decision,12,true);if(!validId(paymentId)||!decision||!["confirmed","rejected"].includes(decision))return Response.json({error:"Valid payment decision required."},{status:400});await supabaseRest("rpc/decide_project_payment",{method:"POST",body:JSON.stringify({target_payment_id:paymentId,decision,reason:cleanText(b?.reason,500)||""})},{userAccessToken:auth.token});return Response.json({ok:true});}
 if(kind==="schedule-archive"){const id=b?.id;if(!validId(id))return Response.json({error:"Valid schedule item required."},{status:400});await supabaseRest(`project_payment_schedule?id=eq.${id}&project_id=eq.${projectId}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({archived_at:b?.archive?new Date().toISOString():null})},"privileged");return Response.json({ok:true});}
 if(kind==="reverse"){const paymentId=b?.paymentId,reason=cleanText(b?.reason,500,true);if(!validId(paymentId)||!reason)return Response.json({error:"A valid payment and reversal reason are required."},{status:400});await supabaseRest("rpc/reverse_project_payment",{method:"POST",body:JSON.stringify({target_payment_id:paymentId,reversal_note:reason})},{userAccessToken:auth.token});return Response.json({ok:true});}
 return Response.json({error:"Unsupported billing action."},{status:400});
}catch{return Response.json({error:"Billing action could not be completed."},{status:409})}}
