import { authorizeMutation, cleanText, cleanUrl } from "@/lib/admin-security";
import { clientProjectStatuses, deliverableStatuses, milestoneStatuses } from "@/lib/client-projects";
import { provisionSupabaseUser, SupabaseRestError, supabaseRest, updateSupabaseUserPassword } from "@/lib/supabase-rest";
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,date=/^\d{4}-\d{2}-\d{2}$/;
const validId=(value:unknown)=>typeof value==="string"&&uuid.test(value);
const optionalDate=(value:unknown)=>{const clean=cleanText(value,10);return clean&&date.test(clean)?clean:null};
const error=()=>Response.json({error:"Client Projects require reviewed migration 006."},{status:409});
export async function POST(request:Request){const auth=await authorizeMutation(request);if(auth.error)return auth.error;const body=await request.json().catch(()=>null) as Record<string,unknown>|null,kind=cleanText(body?.kind,30,true),projectId=body?.projectId;if(!kind||!validId(projectId))return Response.json({error:"Valid operation and project are required."},{status:400});try{
  if(kind==="member"){
    const email=cleanText(body?.email,254,true)?.toLowerCase(),role=cleanText(body?.role,20,true),temporaryPassword=typeof body?.temporaryPassword==="string"?body.temporaryPassword:"";
    if(!email||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!role||!['client','studio'].includes(role))return Response.json({error:"Enter a valid client email and role."},{status:400});
    const existing=await supabaseRest<Array<{id:string}>>(`client_project_members?project_id=eq.${projectId}&email=eq.${encodeURIComponent(email)}&select=id&limit=1`,{},true);
    if(existing.length)return Response.json({ok:true,status:"already_has_access",message:"Client already has access."});
    const addExisting=()=>supabaseRest("rpc/add_client_project_member_by_email",{method:"POST",body:JSON.stringify({target_project_id:projectId,member_email:email,member_role:role})},{userAccessToken:auth.token});
    try{await addExisting();return Response.json({ok:true,status:"member_added",message:"Existing client added to this project."})}catch(cause){
      if(!(cause instanceof SupabaseRestError&&cause.databaseMessage==="No Supabase Auth user exists for this email"))throw cause;
    }
    if(temporaryPassword.length<8)return Response.json({error:"Enter a temporary password of at least 8 characters for a new client."},{status:400});
    let provisioned:{id:string};
    try{provisioned=await provisionSupabaseUser(email,temporaryPassword)}catch{
      try{await addExisting();return Response.json({ok:true,status:"member_added",message:"Existing client added to this project."})}catch{return Response.json({error:"Client access could not be created. Please retry."},{status:502})}
    }
    try{await supabaseRest("client_project_members",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({project_id:projectId,user_id:provisioned.id,email,role})},true)}catch{return Response.json({error:"Client access was created, but project assignment failed. Retry Add Client Access."},{status:409})}
    return Response.json({ok:true,status:"access_created",message:"Client access created."});
  }
  if(kind==="milestone"){const title=cleanText(body?.title,180,true),description=cleanText(body?.description,1200),status=cleanText(body?.status,30,true),sortOrder=Math.max(0,Math.min(1000,Number(body?.sortOrder)||0));if(!title||!status||!milestoneStatuses.includes(status as typeof milestoneStatuses[number]))return Response.json({error:"Complete the milestone fields."},{status:400});await supabaseRest("project_milestones",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({project_id:projectId,title,description:description||"",status,due_date:optionalDate(body?.dueDate),completed_at:status==="completed"?new Date().toISOString():null,sort_order:sortOrder})},true);return Response.json({ok:true})}
  if(kind==="update"){const title=cleanText(body?.title,180,true),updateBody=cleanText(body?.body,2000,true);if(!title||!updateBody)return Response.json({error:"Update title and body are required."},{status:400});await supabaseRest("project_updates",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({project_id:projectId,title,body:updateBody,published_at:new Date().toISOString()})},true);return Response.json({ok:true})}
  if(kind==="deliverable"){const title=cleanText(body?.title,180,true),description=cleanText(body?.description,1200),status=cleanText(body?.status,30,true),externalUrl=cleanUrl(body?.externalUrl);if(!title||!status||!deliverableStatuses.includes(status as typeof deliverableStatuses[number])||externalUrl===null)return Response.json({error:"Complete the deliverable fields with a valid optional URL."},{status:400});await supabaseRest("project_deliverables",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({project_id:projectId,title,description:description||"",status,external_url:externalUrl||null})},true);return Response.json({ok:true})}
  return Response.json({error:"Unsupported Client Project operation."},{status:400});
}catch{return error()}}
export async function PATCH(request:Request){const auth=await authorizeMutation(request);if(auth.error)return auth.error;const body=await request.json().catch(()=>null) as Record<string,unknown>|null,kind=cleanText(body?.kind,30,true),id=body?.id,projectId=body?.projectId;if(!kind||!validId(projectId))return Response.json({error:"Valid operation and project are required."},{status:400});try{
  if(kind==="password-reset"){
    const password=typeof body?.password==="string"?body.password:"";
    if(!validId(id)||body?.confirmed!==true||password.length<8||password.length>128)return Response.json({error:"Confirm a new password between 8 and 128 characters."},{status:400});
    const members=await supabaseRest<Array<{user_id:string}>>(`client_project_members?id=eq.${id}&project_id=eq.${projectId}&role=eq.client&select=user_id&limit=1`,{},"privileged");
    if(!members[0]?.user_id)return Response.json({error:"Client membership was not found."},{status:404});
    try{await updateSupabaseUserPassword(members[0].user_id,password)}catch{return Response.json({error:"Client password could not be reset. Please retry."},{status:502})}
    return Response.json({ok:true,message:"Client password reset."});
  }
  if(kind==="project"){const name=cleanText(body?.name,160,true),clientName=cleanText(body?.clientName,160,true),summary=cleanText(body?.summary,1200),status=cleanText(body?.status,30,true),progress=Math.round(Number(body?.progress)),currentPhase=cleanText(body?.currentPhase,160,true),nextAction=cleanText(body?.nextAction,500);if(!name||!clientName||!status||!clientProjectStatuses.includes(status as typeof clientProjectStatuses[number])||!Number.isInteger(progress)||progress<0||progress>100||!currentPhase)return Response.json({error:"Review the Client Project fields and progress."},{status:400});await supabaseRest(`client_projects?id=eq.${projectId}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({name,client_name:clientName,summary:summary||"",status,progress,current_phase:currentPhase,next_action:nextAction||"",start_date:optionalDate(body?.startDate),target_date:optionalDate(body?.targetDate)})},true);return Response.json({ok:true})}
  if(kind==="milestone-order"){if(!Array.isArray(body?.orderedIds)||body.orderedIds.some(item=>!validId(item)))return Response.json({error:"Invalid milestone order."},{status:400});const ids=[...new Set(body.orderedIds as string[])],rows=await supabaseRest<Array<{id:string}>>(`project_milestones?project_id=eq.${projectId}&status=neq.completed&archived_at=is.null&select=id`,{},true);if(rows.length!==ids.length||rows.some(row=>!ids.includes(row.id)))return Response.json({error:"Active milestones changed. Refresh and try again."},{status:409});await Promise.all(ids.map((milestoneId,sort_order)=>supabaseRest(`project_milestones?id=eq.${milestoneId}&project_id=eq.${projectId}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({sort_order})},true)));return Response.json({ok:true})}
  if(kind==="milestone-archive"&&validId(id)){await supabaseRest(`project_milestones?id=eq.${id}&project_id=eq.${projectId}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({archived_at:body?.archive?new Date().toISOString():null})},{userAccessToken:auth.token});return Response.json({ok:true})}
  if(kind==="milestone"&&validId(id)){const title=cleanText(body?.title,180,true),description=cleanText(body?.description,1200),status=cleanText(body?.status,30,true);if(!title||!status||!milestoneStatuses.includes(status as typeof milestoneStatuses[number]))return Response.json({error:"Complete the milestone fields."},{status:400});await supabaseRest(`project_milestones?id=eq.${id}&project_id=eq.${projectId}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({title,description:description||"",status,due_date:optionalDate(body?.dueDate),completed_at:status==="completed"?new Date().toISOString():null})},true);return Response.json({ok:true})}
  if(kind==="deliverable"&&validId(id)){const title=cleanText(body?.title,180,true),description=cleanText(body?.description,1200),status=cleanText(body?.status,30,true),externalUrl=cleanUrl(body?.externalUrl);if(!title||!status||!deliverableStatuses.includes(status as typeof deliverableStatuses[number])||externalUrl===null)return Response.json({error:"Complete the deliverable fields with a valid optional URL."},{status:400});await supabaseRest(`project_deliverables?id=eq.${id}&project_id=eq.${projectId}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({title,description:description||"",status,external_url:externalUrl||null})},true);return Response.json({ok:true})}
  return Response.json({error:"Unsupported Client Project update."},{status:400});
}catch{return error()}}
export async function DELETE(request:Request){const auth=await authorizeMutation(request);if(auth.error)return auth.error;const body=await request.json().catch(()=>null) as Record<string,unknown>|null,kind=cleanText(body?.kind,30,true),id=body?.id,projectId=body?.projectId;if(!kind||!validId(id)||!validId(projectId)||!['milestone','update','deliverable','member'].includes(kind))return Response.json({error:"Valid child record is required."},{status:400});const tables:Record<string,string>={milestone:"project_milestones",update:"project_updates",deliverable:"project_deliverables",member:"client_project_members"};try{await supabaseRest(`${tables[kind]}?id=eq.${id}&project_id=eq.${projectId}`,{method:"DELETE",headers:{Prefer:"return=minimal"}},true);return Response.json({ok:true})}catch{return Response.json({error:kind==="milestone"?"Only an unused pending milestone draft can be permanently deleted. Archive historical milestones instead.":"The record could not be removed."},{status:409})}}
