import { DynamicText, T } from "@/i18n/language-context";
import { publicMetadata } from "@/lib/seo";
import Link from "next/link";
import { getPublishedProjects } from "@/lib/studio-data";
import { ResponsiveMedia } from "@/components/ui/primitives";
import "./work.css";
export const metadata = publicMetadata("Selected Work", "Client case studies in custom web development, ecommerce and business software from Taoshiflex Studio.", "/work");
export const revalidate = 60;
export default async function WorkPage(){const projects=await getPublishedProjects();return <div className="work-index container"><header><p className="eyebrow"><T id="work.selectedWorkCurated"/></p><h1 className="display"><T id="work.businessProblems"/><br/><span className="title-accent"><T id="work.madeTangible"/></span></h1><p><T id="work.aFocusedSelectionOfCommercialAndInternalProductWork"/></p></header><div className={`work-list ${projects.length?"":"empty"}`}>{projects.length?projects.map((project,index)=><article key={project.slug} style={{"--accent":project.accent} as React.CSSProperties}><div className="work-number technical">{String(index+1).padStart(2,"0")}</div><Link href={`/work/${project.slug}`}><ResponsiveMedia accent={project.accent} className="work-cover-media" fit="contain" label={project.name} media={project.coverMedia} priority={index===0}/></Link><div><p className="technical"><DynamicText text={project.category}/> / <DynamicText text={project.status}/></p><h2><Link href={`/work/${project.slug}`}>{project.name}</Link></h2><p><DynamicText text={project.summary} slug={project.slug}/></p><Link className="action" href={`/work/${project.slug}`}><T id="work.readCaseStudy"/> <span aria-hidden>↗</span></Link></div></article>):<div><p className="eyebrow"><T id="work.editorialPause"/></p><h2><T id="work.noProjectIsCurrentlyPublished"/></h2><p><T id="work.thePublicSelectionIsIntentionallyEmptyWhileTheStudio"/></p><Link className="action" href="/start-a-project"><T id="work.discussRelevantWork"/></Link></div>}</div></div>}
