"use client";
import { useState,type FormEvent } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { ToastRegion,useToasts } from "@/components/ui/toast";
import { productStatuses } from "@/lib/product-contract";
import { projectMediaPublicUrl } from "@/lib/project-media-url";
import type { Product } from "@/types/content";
import "./products-admin.css";
type Media={id:string;role:string;alt:string;sort_order:number;storage_path:string};
export type AdminProduct=Omit<Product,'media'> & {published:boolean;show_repository:boolean;source_repository_private:boolean;sort_order:number;product_media:Media[]};
const fields=[['name','Name',160],['slug','Slug',80],['tagline','Tagline',200],['category','Category',80],['accent','Accent (#hex)',7],['pricing_model','Pricing model',160],['product_url','Public product / demo URL',500],['repository_url','Public repository URL (optional)',500]] as const;
const narratives=[['summary','Summary',500],['story','Product story',8000],['problem','Problem',4000],['solution','Solution',4000],['roadmap','Current status / roadmap context',4000]] as const;
export function ProductsAdmin({products}:{products:AdminProduct[]}) {
  const [selected,setSelected]=useState<string>('');const [search,setSearch]=useState('');
  const product=products.find(item=>item.id===selected);
  return <div className="products-admin"><div className="products-admin-list"><label>Find product<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><button type="button" onClick={()=>setSelected('')}>+ Create product</button>{products.filter(item=>`${item.name} ${item.status}`.toLowerCase().includes(search.toLowerCase())).map(item=><button type="button" key={item.id} aria-pressed={selected===item.id} onClick={()=>setSelected(item.id)}><strong>{item.name}</strong><small>{item.published?'Published':'Draft / archived'} · {item.status}{item.featured?' · Featured':''}</small></button>)}</div><ProductEditor key={product?.id??'new'} product={product} onCreated={setSelected}/></div>;
}
function ProductEditor({product,onCreated}:{product?:AdminProduct;onCreated:(id:string)=>void}) {
  const router=useRouter();const {toasts,toast,dismiss}=useToasts();const [busy,setBusy]=useState(false);const [privateSource,setPrivateSource]=useState(product?.source_repository_private??false);const [published,setPublished]=useState(product?.published??false);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);const data=new FormData(event.currentTarget);const body:Record<string,unknown>={id:product?.id};
    for(const [key] of [...fields,...narratives])body[key]=String(data.get(key)??'');
    for(const key of ['features','technologies'])body[key]=String(data.get(key)??'').split('\n').map(s=>s.trim()).filter(Boolean);
    Object.assign(body,{status:data.get('status'),launch_date:data.get('launch_date')||null,sort_order:Number(data.get('sort_order')),published,featured:published&&data.has('featured'),source_repository_private:privateSource,show_repository:!privateSource&&data.has('show_repository'),repository_url:privateSource?'':body.repository_url});
    try{const response=await fetch('/api/studio/products',{method:product?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error);toast('success','Product saved. Public changes appear within a minute.');onCreated(result.id);router.refresh();}catch(error){toast('error',error instanceof Error?error.message:'Could not save product.');}finally{setBusy(false);}}
  async function archive(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!product||busy)return;setBusy(true);const confirmName=new FormData(event.currentTarget).get('confirmName');try{const response=await fetch('/api/studio/products',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:product.id,confirmName})});const result=await response.json();if(!response.ok)throw new Error(result.error);setPublished(false);toast('success','Product archived. Content and images are preserved.');router.refresh();}catch(error){toast('error',error instanceof Error?error.message:'Could not archive.');}finally{setBusy(false);}}
  return <div className="product-editor"><h2>{product?product.name:'New product'}</h2><form onSubmit={save}><div className="product-editor-grid">{fields.map(([key,label,max])=><label key={key}>{label}<input name={key} maxLength={max} required={['name','slug','category','accent'].includes(key)} disabled={key==='repository_url'&&privateSource} defaultValue={String(product?.[key]??(key==='accent'?'#b89055':key==='category'?'Software':''))} type={key.endsWith('_url')?'url':'text'}/></label>)}<label>Status<select name="status" defaultValue={product?.status??'In Development'}>{productStatuses.map(status=><option key={status}>{status}</option>)}</select></label><label>Launch date<input name="launch_date" type="date" defaultValue={product?.launch_date??''}/></label><label>Display order<input name="sort_order" type="number" min={-100000} max={100000} defaultValue={product?.sort_order??0}/></label></div>
    {narratives.map(([key,label,max])=><label key={key}>{label}<textarea name={key} maxLength={max} rows={key==='summary'?3:5} defaultValue={product?.[key]??''}/></label>)}<div className="product-editor-grid">{(['features','technologies'] as const).map(key=><label key={key}>{key==='features'?'Key features':'Technologies'} (one per line, up to 30)<textarea name={key} rows={5} defaultValue={product?.[key].join('\n')??''}/></label>)}</div>
    <fieldset><legend>Visibility & source privacy</legend><label className="product-check"><input type="checkbox" checked={privateSource} onChange={e=>setPrivateSource(e.target.checked)}/>Uses a private source repository</label><p>Private source URLs do not belong in public content. This option removes the repository link. Product descriptions, screenshots and a safe public demo URL still work.</p><label className="product-check"><input type="checkbox" name="show_repository" disabled={privateSource} defaultChecked={product?.show_repository}/>Show the optional public repository</label><label className="product-check"><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)}/>Publish product</label><label className="product-check"><input type="checkbox" name="featured" disabled={!published} defaultChecked={product?.featured}/>Feature on homepage</label></fieldset><button disabled={busy}>{busy?'Saving…':product?'Save product':'Create product draft'}</button></form>
    {product&&<><ProductMediaEditor product={product}/><details className="product-archive"><summary>Archive product</summary><p>This unpublishes the product and removes it from featured products. Images and content remain available in Admin.</p><form onSubmit={archive}><label>Type “{product.name}” to confirm<input name="confirmName" required autoComplete="off"/></label><button className="danger" disabled={busy}>Confirm archive</button></form></details></>}
    <ToastRegion toasts={toasts} dismiss={dismiss}/></div>;
}
function ProductMediaEditor({product}:{product:AdminProduct}) {
  const router=useRouter();const {toasts,toast,dismiss}=useToasts();const [busy,setBusy]=useState(false);
  async function mutate(event:FormEvent<HTMLFormElement>,method:'POST'|'PATCH'|'DELETE',id?:string){event.preventDefault();if(busy)return;setBusy(true);const form=event.currentTarget,data=new FormData(form);data.set('productId',product.id);try{const response=await fetch('/api/studio/product-media',{method,headers:method==='POST'?undefined:{'Content-Type':'application/json'},body:method==='POST'?data:JSON.stringify({id,alt:data.get('alt'),sort_order:Number(data.get('sort_order'))})});const result=await response.json();if(!response.ok)throw new Error(result.error);toast(result.warning?'error':'success',result.warning?`${result.warning} Object: ${result.cleanupPath}`:'Product media updated.');if(method==='POST')form.reset();router.refresh();}catch(error){toast('error',error instanceof Error?error.message:'Media update failed.');}finally{setBusy(false);}}
  return <section className="product-media-editor"><h3>Product images</h3><p>Upload only screenshots intended for public display. JPEG, PNG, WebP or AVIF, up to 6 MB.</p><form onSubmit={e=>mutate(e,'POST')}><label>Image<input type="file" name="file" accept="image/jpeg,image/png,image/webp,image/avif" required/></label><label>Role<select name="role"><option value="cover">Cover (replaces current cover)</option><option value="gallery">Gallery</option></select></label><label>Replace existing image (optional)<select name="replaceId"><option value="">New image / selected role</option>{product.product_media.map(media=><option key={media.id} value={media.id}>{media.role}: {media.alt}</option>)}</select></label><label>Alt text<input name="alt" required maxLength={240}/></label><button disabled={busy}>Upload image</button></form><div className="product-media-grid">{product.product_media.map(media=><article key={media.id}><Image src={projectMediaPublicUrl(media.storage_path)} alt={media.alt} width={480} height={300} unoptimized/><p>{media.role}</p><form onSubmit={e=>mutate(e,'PATCH',media.id)}><label>Alt text<input name="alt" required maxLength={240} defaultValue={media.alt}/></label><label>Order<input name="sort_order" type="number" min={-100000} max={100000} defaultValue={media.sort_order}/></label><button disabled={busy}>Save image details</button></form><details><summary>Delete image</summary><p>Permanently remove this image from the product and Storage?</p><form onSubmit={e=>mutate(e,'DELETE',media.id)}><button className="danger" disabled={busy}>Confirm image deletion</button></form></details></article>)}</div><ToastRegion toasts={toasts} dismiss={dismiss}/></section>;
}
