export type ProjectMedia = { id: string; kind: "image"; role?: "cover" | "gallery"; alt: string; aspect: "landscape" | "portrait" | "square"; src?: string; storagePath?:string; width?:number; height?:number; mime?:string; sortOrder?:number };
export type Project = { id?: string; slug: string; name: string; client: string; category: "Commerce" | "Business System" | "Digital Product" | "Website"; year: string; status: string; summary: string; context: string; challenge: string; approach: string; solution: string; result: string; capabilities: string[]; features: string[]; technicalNotes: string[]; accent: string; coverMedia?: ProjectMedia; media: ProjectMedia[]; repositoryUrl?: string; showRepository?: boolean; liveUrl?: string; behanceUrl?: string; facebookUrl?: string; githubRepositoryId?: number; githubUpdatedAt?: string; featured?: boolean; published?: boolean; sortOrder?: number; createdAt?: string; updatedAt?: string };
export type Capability = { id: string; number: string; title: string; value: string; description: string; nodes: string[] };
export type ProcessStage = { id: string; title: string; what: string; why: string; deliverable: string };
export type PublicReview = { id: string; reviewer_name: string; reviewer_role: string; reviewer_company: string; rating: number; review_text: string; featured: boolean; project_slug: string | null; project_name: string | null; accent: string | null };
export type Testimonial = { quote: string; author: string; role: string; published: boolean };
export type Inquiry = { projectType: string; stage: string; goals: string[]; budget: string; timeline: string; details: string; name: string; business: string; email: string; phone?: string };
export type SiteSettings = { name: string; description: string; url: string; location: string; email: string };
export type ServicePackage = { id: string; slug: string; name: string; priceFrom: number | null; currency: "BDT"; description: string; features: string[]; deliveryEstimate: string; revisions?: string; support?: string; category: string; featured: boolean; enabled: boolean; sortOrder: number };
export type AssistantSettings = { enabled: boolean; name: string; greeting: string; instructions: string; knowledgeCategories: string[]; showPricing: boolean; leadCapture: boolean; handoffUrl: string; maximumMessages: number; logConversations: boolean };

export type Product = { id: string; slug: string; name: string; tagline: string; summary: string; story: string; problem: string; solution: string; roadmap: string; status: string; category: string; accent: string; features: string[]; technologies: string[]; product_url: string | null; repository_url: string | null; pricing_model: string; launch_date: string | null; featured: boolean; media: ProjectMedia[] };
