import type { ServicePackage } from "@/types/content";

export const servicePackages: ServicePackage[] = [
  { id:"one-page",slug:"one-page-website",name:"One-Page Website",priceFrom:14999,currency:"BDT",description:"A focused, custom landing page for a clear offer or campaign.",features:["One custom landing page","Up to 6 sections","WhatsApp or contact integration","Basic SEO","Responsive development","2 revision rounds"],deliveryEstimate:"5–7 working days",revisions:"2 rounds",category:"Website",featured:false,enabled:true,sortOrder:1 },
  { id:"business",slug:"business-website",name:"Business Website",priceFrom:27999,currency:"BDT",description:"A credible, brand-aligned presence built to explain, reassure and convert.",features:["Up to 5 pages","Brand-aligned custom design","Services or portfolio","Contact or lead form","Responsive development","Basic SEO","3 revision rounds"],deliveryEstimate:"10–12 working days",revisions:"3 rounds",category:"Website",featured:true,enabled:true,sortOrder:2 },
  { id:"commerce",slug:"e-commerce-website",name:"E-Commerce Website",priceFrom:49999,currency:"BDT",description:"A practical storefront connecting discovery, checkout and basic operations.",features:["Up to 30 initial products","Product and catalog experience","Search and filtering","Cart and checkout","Payment setup where applicable","Cash on delivery","Basic store admin"],deliveryEstimate:"18–21 working days",category:"Commerce",featured:false,enabled:true,sortOrder:3 },
  { id:"advanced-commerce",slug:"advanced-e-commerce",name:"Advanced E-Commerce",priceFrom:79999,currency:"BDT",description:"A custom commerce system for businesses with deeper customer and operational needs.",features:["Custom store experience","Customer accounts","Wishlist","Inventory and order management","Order-status tracking","Product reviews","Advanced store management"],deliveryEstimate:"Approximately 28 working days",support:"30-day post-launch bug and support window",category:"Commerce",featured:false,enabled:true,sortOrder:4 },
  { id:"platform",slug:"custom-platform",name:"Custom Platform / Web Application",priceFrom:null,currency:"BDT",description:"Purpose-built software scoped around your users, workflows and operational reality.",features:["Discovery and scope definition","Custom experience architecture","Project-specific engineering plan","Proposal based on verified requirements"],deliveryEstimate:"Defined after discovery",category:"Platform",featured:false,enabled:true,sortOrder:5 },
];
