import type { Project } from "@/types/content";

export const projects: Project[] = [
  { slug: "kothas-aura", name: "Kotha's Aura", client: "Kotha's Aura", category: "Commerce", year: "2026", status: "In development", summary: "A considered commerce experience connecting storytelling, product discovery and the realities of order operations.", context: "An emerging consumer brand needed a digital storefront with enough character to feel distinct and enough structure to support daily commerce.", challenge: "Bring brand expression and operational clarity into one experience without burying customers beneath interface decoration.", approach: "We mapped the purchase journey alongside the order workflow, then built a visual system where editorial storytelling and product utility reinforce each other.", solution: "A responsive storefront, structured catalog, deliberate checkout journey and an operations-ready order foundation.", result: "The core customer and order experiences are in active development. No commercial performance claims are made before launch.", capabilities: ["Product strategy", "Commerce UX", "Interface design", "Full-stack engineering"], features: ["Editorial catalog", "Product detail system", "Checkout journey", "Order operations"], technicalNotes: ["Next.js application architecture", "Typed product and order domains", "Deployment-ready environment separation"], accent: "#b5884c", media: [{ id: "ka-1", kind: "image", alt: "Kotha's Aura storefront art direction placeholder", aspect: "landscape" }, { id: "ka-2", kind: "image", alt: "Kotha's Aura product interface placeholder", aspect: "portrait" }] },
  { slug: "redflint", name: "RedFlint", client: "RedFlint", category: "Business System", year: "2026", status: "Product foundation", summary: "A clear operational platform designed to make complex business activity easier to see, manage and improve.", context: "RedFlint is structured as a business system where operational information and action need to live in the same dependable environment.", challenge: "Translate interconnected workflows into an interface that feels direct to everyday users while remaining extensible behind the scenes.", approach: "We treated navigation, data relationships and repeat actions as a single system rather than separate screens.", solution: "A modular product foundation with role-aware workflows, legible information hierarchy and reusable operational patterns.", result: "The product foundation and core experience direction are established; broader functionality remains intentionally staged.", capabilities: ["Systems thinking", "Product UX", "Design systems", "Application engineering"], features: ["Operational overview", "Workflow modules", "Structured records", "Role-ready foundation"], technicalNotes: ["Modular domain architecture", "Strict TypeScript contracts", "Accessible interaction patterns"], accent: "#9b463e", media: [{ id: "rf-1", kind: "image", alt: "RedFlint operational dashboard placeholder", aspect: "landscape" }, { id: "rf-2", kind: "image", alt: "RedFlint workflow view placeholder", aspect: "square" }] },
  { slug: "quran-companion", name: "Quran Companion", client: "Internal product", category: "Digital Product", year: "2026", status: "Active prototype", summary: "A calm reading companion shaped around trustworthy source structure, focus and everyday continuity.", context: "This internal product explores how a sensitive, content-rich reading experience can stay simple while supporting continued use.", challenge: "Design for reverence and focus while making navigation, translations and reading state practical across devices.", approach: "We prioritized content integrity, typographic rhythm and quiet interactions, then designed supporting tools around the reading experience.", solution: "A responsive reading product with source-aware content architecture and a restrained companion interface.", result: "An active internal prototype used to validate the content model and core reading experience.", capabilities: ["Product direction", "Content architecture", "Reading UX", "Frontend engineering"], features: ["Focused reader", "Translation structure", "Reading continuity", "Responsive navigation"], technicalNotes: ["Verified source import workflow", "Offline-ready web foundation", "API-separated architecture"], accent: "#6f806c", media: [{ id: "qc-1", kind: "image", alt: "Quran Companion reading interface placeholder", aspect: "landscape" }, { id: "qc-2", kind: "image", alt: "Quran Companion mobile reader placeholder", aspect: "portrait" }] },
];

export const getProject = (slug: string) => projects.find((project) => project.slug === slug);
