import { NextRequest } from "next/server";
import { isSupabaseServerConfigured, supabaseRest } from "@/lib/supabase-rest";
import { rateLimit } from "@/lib/rate-limit";
import type { Inquiry } from "@/types/content";

const limits={projectType:80,stage:80,budget:80,timeline:80,details:3000,name:120,business:160,email:254,phone:40};
function text(value:unknown,max:number){return typeof value==="string"?value.trim().slice(0,max):""}
function validate(body:unknown):Inquiry|null{if(!body||typeof body!=="object")return null;const value=body as Record<string,unknown>;const inquiry={projectType:text(value.projectType,limits.projectType),stage:text(value.stage,limits.stage),goals:Array.isArray(value.goals)?value.goals.slice(0,8).map((item)=>text(item,80)).filter(Boolean):[],budget:text(value.budget,limits.budget),timeline:text(value.timeline,limits.timeline),details:text(value.details,limits.details),name:text(value.name,limits.name),business:text(value.business,limits.business),email:text(value.email,limits.email).toLowerCase(),phone:text(value.phone,limits.phone)};if(!inquiry.projectType||!inquiry.stage||!inquiry.goals.length||!inquiry.budget||!inquiry.timeline||inquiry.details.length<20||!inquiry.name||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(inquiry.email))return null;return inquiry}
export async function POST(request:NextRequest){const ip=request.headers.get("x-forwarded-for")?.split(",")[0]??"unknown";if(!rateLimit(`inquiry:${ip}`,5,60*60*1000))return Response.json({error:"Too many requests. Please try again later."},{status:429});if(!isSupabaseServerConfigured())return Response.json({error:"Project inquiries are temporarily unavailable. Please contact the Studio through a configured channel."},{status:503});let body:unknown;try{body=await request.json()}catch{return Response.json({error:"Invalid request."},{status:400})}const inquiry=validate(body);if(!inquiry)return Response.json({error:"Please review the brief and contact details."},{status:400});try{await supabaseRest("inquiries",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({email:inquiry.email,payload:inquiry,status:"new"})},true);return Response.json({ok:true})}catch{return Response.json({error:"We could not save your inquiry. Nothing was submitted; please try again."},{status:502})}}
