"use client";

import Link from "next/link";
import { useRef, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { inquirySteps } from "@/lib/inquiry-config";
import { ToastRegion, useToasts } from "@/components/ui/toast";
import type { Inquiry } from "@/types/content";

type Key = "projectType" | "stage" | "goals" | "budget" | "timeline";
type SubmitState = "idle" | "sending" | "success" | "error";
const empty: Inquiry = { projectType:"", stage:"", goals:[], budget:"", timeline:"", details:"", name:"", business:"", email:"", phone:"" };
const total = 7;

export function InquiryFlow() {
  const [step,setStep]=useState(0),[data,setData]=useState(empty),[touched,setTouched]=useState(false),[submitState,setSubmitState]=useState<SubmitState>("idle"),[message,setMessage]=useState(""),[reference,setReference]=useState("");
  const submitting=useRef(false),reduce=useReducedMotion(),{toasts,toast,dismiss}=useToasts();
  const valid=step<5?(step===2?data.goals.length>0:Boolean(data[inquirySteps[step].id as Key])):step===5?data.details.trim().length>=20:Boolean(data.name.trim()&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email));
  function choose(key:Key,value:string,multiple?:boolean){setTouched(false);setData(prev=>({...prev,[key]:multiple?(prev.goals.includes(value)?prev.goals.filter(x=>x!==value):[...prev.goals,value]):value}))}
  function next(){setTouched(true);if(valid&&step<total-1){setStep(value=>value+1);setTouched(false)}}
  function back(){if(submitState!=="sending"){setStep(value=>Math.max(0,value-1));setTouched(false)}}
  async function submit(){setTouched(true);if(!valid||submitting.current)return;submitting.current=true;setSubmitState("sending");setMessage("");try{const response=await fetch("/api/inquiries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await response.json() as {error?:string;reference?:string};if(!response.ok||!result.reference)throw new Error(result.error||"Submission failed.");setReference(result.reference);setSubmitState("success");toast("success",`Project brief received · ${result.reference}`)}catch(error){const text=error instanceof Error?error.message:"We could not submit your brief.";setSubmitState("error");setMessage(text);toast("error",text)}finally{submitting.current=false}}
  const validation=touched&&!valid?(step===5?"Please share at least 20 characters.":step===6?"Please add your name and a valid email.":"Choose at least one option to continue."):"";
  return <><div className="inquiry-layout"><div className="inquiry-form">{submitState==="success"?<SuccessReceipt reference={reference}/>:<><div className="step-head technical"><span>Step {String(step+1).padStart(2,"0")} / 07</span><span>{Math.round(((step+1)/total)*100)}%</span></div><div className="progress"><i style={{width:`${((step+1)/total)*100}%`}}/></div><AnimatePresence mode="wait"><motion.div key={step} className="step-panel" initial={reduce?false:{opacity:0,x:24}} animate={{opacity:1,x:0}} exit={reduce?undefined:{opacity:0,x:-24}} transition={{duration:.35}}>{step<5?<ChoiceStep step={step} data={data} choose={choose}/>:step===5?<div><p className="eyebrow">The brief</p><h2>Tell us about it.</h2><label htmlFor="details">What are you trying to achieve?</label><textarea id="details" maxLength={3000} rows={7} value={data.details} onChange={event=>setData({...data,details:event.target.value})} placeholder="A little context about the business, problem and desired outcome…"/><small>At least 20 characters. Clear and simple is perfect.</small></div>:<ContactStep data={data} setData={setData}/>}</motion.div></AnimatePresence><div aria-live="polite" className={`form-error ${submitState}`}>{message||validation}</div><div className="step-actions">{step>0?<button type="button" className="back" disabled={submitState==="sending"} onClick={back}>← Back</button>:<span/>}{step<6?<button type="button" className="next" disabled={!valid} onClick={next}>Continue →</button>:<button type="button" className="next" disabled={submitState==="sending"} aria-busy={submitState==="sending"} onClick={submit}>{submitState==="sending"?"Sending…":"Send project brief"}</button>}</div></>}</div><Brief data={data} step={step} submitted={submitState==="success"}/></div><ToastRegion toasts={toasts} dismiss={dismiss}/></>;
}

function SuccessReceipt({reference}:{reference:string}){return <motion.section className="inquiry-receipt" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} aria-labelledby="receipt-title"><span className="receipt-mark" aria-hidden>✓</span><p className="eyebrow">Submitted / Not yet accepted</p><h2 id="receipt-title">Project brief received</h2><p>We’ll review the brief and reply using the email you provided.</p><dl><dt>Submission reference</dt><dd>{reference}</dd></dl><p className="receipt-note">Keep this reference if you need to contact the Studio. Submission does not mean the project has been accepted or started.</p><div className="receipt-actions"><Link className="action action-solid" href="/">Return home</Link><Link className="action" href="/work">Explore work <span aria-hidden>↗</span></Link></div></motion.section>}
function ChoiceStep({step,data,choose}:{step:number;data:Inquiry;choose:(key:Key,value:string,multiple?:boolean)=>void}){const current=inquirySteps[step],key=current.id as Key;return <div><p className="eyebrow">Project qualifier</p><h2>{current.label}</h2><div className="choice-grid">{current.options.map(option=>{const selected=key==="goals"?data.goals.includes(option):data[key]===option;return <button type="button" key={option} aria-pressed={selected} onClick={()=>choose(key,option,"multiple" in current&&current.multiple)}><i aria-hidden>{selected?"×":"+"}</i>{option}</button>})}</div></div>}
function ContactStep({data,setData}:{data:Inquiry;setData:(data:Inquiry)=>void}){return <div><p className="eyebrow">Last step</p><h2>Who should we reply to?</h2><div className="fields"><label>Name *<input maxLength={120} required value={data.name} autoComplete="name" onChange={event=>setData({...data,name:event.target.value})}/></label><label>Business<input maxLength={160} value={data.business} autoComplete="organization" onChange={event=>setData({...data,business:event.target.value})}/></label><label>Email *<input maxLength={254} required type="email" value={data.email} autoComplete="email" onChange={event=>setData({...data,email:event.target.value})}/></label><label>Phone / WhatsApp <span>optional</span><input maxLength={40} type="tel" value={data.phone} autoComplete="tel" onChange={event=>setData({...data,phone:event.target.value})}/></label></div></div>}
function Brief({data,step,submitted}:{data:Inquiry;step:number;submitted:boolean}){const rows=[["Project",data.projectType],["Stage",data.stage],["Goal",data.goals.join(", ")],["Investment",data.budget],["Timeline",data.timeline]];return <aside className="live-brief"><div><p className="technical">Live / Project brief</p><span className="brief-x">×</span></div><dl>{rows.map(([label,value])=><motion.div key={label} animate={{opacity:value?1:.25}}><dt>{label}</dt><dd>{value||"Not answered yet"}</dd></motion.div>)}</dl><p className="technical">Brief state / {submitted?"Submitted":String(step+1).padStart(2,"0")}</p></aside>}
