"use client";
import { useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { inquirySteps } from "@/lib/inquiry-config";
import type { Inquiry } from "@/types/content";
type Key="projectType"|"stage"|"goals"|"budget"|"timeline";
const empty:Inquiry={projectType:"",stage:"",goals:[],budget:"",timeline:"",details:"",name:"",business:"",email:"",phone:""};
const total=7;
export function InquiryFlow(){const [step,setStep]=useState(0);const [data,setData]=useState(empty);const [touched,setTouched]=useState(false);const reduce=useReducedMotion();const valid=step<5?(step===2?data.goals.length>0:Boolean(data[inquirySteps[step].id as Key])):step===5?data.details.trim().length>=20:Boolean(data.name.trim()&&data.email.includes("@"));function choose(key:Key,value:string,multiple?:boolean){setTouched(false);setData(prev=>({...prev,[key]:multiple?(prev.goals.includes(value)?prev.goals.filter(x=>x!==value):[...prev.goals,value]):value}))}function next(){setTouched(true);if(valid&&step<total-1){setStep(v=>v+1);setTouched(false)}}function back(){setStep(v=>Math.max(0,v-1));setTouched(false)}return <div className="inquiry-layout"><div className="inquiry-form"><div className="step-head technical"><span>Step {String(step+1).padStart(2,"0")} / 07</span><span>{Math.round(((step+1)/total)*100)}%</span></div><div className="progress"><i style={{width:`${((step+1)/total)*100}%`}}/></div><AnimatePresence mode="wait"><motion.div key={step} className="step-panel" initial={reduce?false:{opacity:0,x:24}} animate={{opacity:1,x:0}} exit={reduce?undefined:{opacity:0,x:-24}} transition={{duration:.35}}>{step<5?<ChoiceStep step={step} data={data} choose={choose}/>:step===5?<div><p className="eyebrow">The brief</p><h2>Tell us about it.</h2><label htmlFor="details">What are you trying to achieve?</label><textarea id="details" rows={7} value={data.details} onChange={e=>setData({...data,details:e.target.value})} placeholder="A little context about the business, problem and desired outcome…"/><small>At least 20 characters. Clear and simple is perfect.</small></div>:<ContactStep data={data} setData={setData}/>}</motion.div></AnimatePresence><div aria-live="polite" className="form-error">{touched&&!valid?(step===5?"Please share at least 20 characters.":step===6?"Please add your name and a valid email.":"Choose at least one option to continue."):""}</div><div className="step-actions">{step>0?<button type="button" onClick={back}>← Back</button>:<span/>}{step<6?<button type="button" className="next" onClick={next}>Continue →</button>:<button type="button" className="next" disabled title="Supabase is not configured in Phase 1">Submission unavailable in preview</button>}</div>{step===6?<p className="dev-note">This Phase 1 preview does not persist inquiries. Your answers remain only in this browser session.</p>:null}</div><Brief data={data} step={step}/></div>}
function ChoiceStep({step,data,choose}:{step:number;data:Inquiry;choose:(key:Key,value:string,multiple?:boolean)=>void}){const current=inquirySteps[step];const key=current.id as Key;return <div><p className="eyebrow">Project qualifier</p><h2>{current.label}</h2><div className="choice-grid">{current.options.map(option=>{const selected=key==="goals"?data.goals.includes(option):data[key]===option;return <button type="button" key={option} aria-pressed={selected} onClick={()=>choose(key,option,"multiple" in current&&current.multiple)}><i aria-hidden>{selected?"×":"+"}</i>{option}</button>})}</div></div>}
function ContactStep({data,setData}:{data:Inquiry;setData:(data:Inquiry)=>void}){return <div><p className="eyebrow">Last step</p><h2>Who should we reply to?</h2><div className="fields"><label>Name *<input value={data.name} autoComplete="name" onChange={e=>setData({...data,name:e.target.value})}/></label><label>Business<input value={data.business} autoComplete="organization" onChange={e=>setData({...data,business:e.target.value})}/></label><label>Email *<input type="email" value={data.email} autoComplete="email" onChange={e=>setData({...data,email:e.target.value})}/></label><label>Phone / WhatsApp <span>optional</span><input type="tel" value={data.phone} autoComplete="tel" onChange={e=>setData({...data,phone:e.target.value})}/></label></div></div>}
function Brief({data,step}:{data:Inquiry;step:number}){const rows=[ ["Project",data.projectType],["Stage",data.stage],["Goal",data.goals.join(", ")],["Investment",data.budget],["Timeline",data.timeline] ];return <aside className="live-brief"><div><p className="technical">Live / Project brief</p><span className="brief-x">×</span></div><dl>{rows.map(([label,value],index)=><motion.div key={label} animate={{opacity:value?1:.25}}><dt>0{index+1} / {label}</dt><dd>{value||"Not answered yet"}</dd></motion.div>)}</dl><p className="technical">Brief state / {String(step+1).padStart(2,"0")}</p></aside>}
